services:
  db:    
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    environment:  
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ONETIME_PASSWORD: onetime
    restart: always
    env_file: ./.env
    ports:
      - "6033:3306"
    volumes:  
       - ./DB:/docker-entrypoint-initdb.d

  backend:  
    build: ./www
    container_name: backend
    depends_on: 
      - db
    ports:   
      - 8080:3000
