services:
  mysql:    
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container  
    environment:  
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ONETIME_PASSWORD: onetime
    restart: always
    env_file: ./.env
    ports:
      - "6033:3306"
    volumes:  
       - ./DB:/docker-entrypoint-initdb.d

  node:   
      image: node:latest  
      container_name: node-container  
      ports:   
       - 80:80 
      
  app-data:    
    image: node
    container_name: app-data-container  
    volumes:  
      - ./www/:/var/www/
    command: "true"

  python:    
    image: python
    container_name: python  
    env_file: ./.env
    expose:  
      - 9000  
    volumes_from:  
      - app-data  
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=3307
